services:
  postgres-users:
    image: postgres:16-alpine
    container_name: postgres-users
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_users_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openwebui"]
      interval: 10s
      timeout: 5s
      retries: 5

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    depends_on:
      postgres-users:
        condition: service_healthy
    environment:
      - OPENAI_API_BASE_URL=http://litellm-1:4000/v1
      - OPENAI_API_KEY=${LITELLM_MASTER_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-users:5432/${POSTGRES_DB}
      - RESET_CONFIG_ON_START=${RESET_CONFIG_ON_START}
      - ENABLE_SIGNUP=${ENABLE_SIGNUP}
      - ENABLE_OLLAMA_API=${ENABLE_OLLAMA_API}
      - ENABLE_OPENAI_API=${ENABLE_OPENAI_API}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - DEFAULT_USER_ROLE=${DEFAULT_USER_ROLE}
      - WEBUI_AUTH=${WEBUI_AUTH}
      - WEBUI_NAME=${WEBUI_NAME}
      - DEFAULT_MODELS=${DEFAULT_MODELS}
      - UVICORN_WORKERS=${UVICORN_WORKERS}
      - BYPASS_MODEL_ACCESS_CONTROL=${BYPASS_MODEL_ACCESS_CONTROL}
    volumes:
      - open_webui_data:/app/backend/data
    networks:
      - internal
      - web
      - monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_users_data:
    driver: local